version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.22.0
    container_name: temporal
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_DB=temporal
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres
    networks:
      - temporal-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - temporal-network

volumes:
  postgres_data:

networks:
  temporal-network:
    driver: bridge
